config/routes.rb
Rails.application.routes.draw do
  get '/reviews/top_rated', to: 'reviews#top_rated'
  
  resources :reviews
  
  resources :recipes do 
    resources :reviews, only: [:index, :new, :create]
  end


  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :reviews, :dependent => :destroy
    has_many :users, through: :reviews
    accepts_nested_attributes_for :reviews

    validates :title, presence: true, uniqueness: true
    validates :ingredients, :instructions, presence: true
    
    def self.ordered_alphabetically
        self.order(title: :asc)
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :recipe
    belongs_to :user
    #accepts_nested_attributes_for :recipe

    validates :comment, presence: true

    def recipes_attributes=(attr)
        self.recipe = Recipe.find_or_create_by(title: attr[:title])
    end

    def self.top_rated
        self.order(stars: :desc)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :recipes, through: :reviews

    has_secure_password

    validates :username, :email, presence: true, uniqueness: true
    
    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
    include ReviewsHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :recipe_find, only: [:show, :update, :edit, :destroy]

    def new
        @recipe = Recipe.new
        @recipe.reviews.build
    end

    def index
        @recipes = Recipe.all.ordered_alphabetically
    end

    def show
    end
    
    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.valid?
            @recipe.save
            redirect_to recipe_path(@recipe)
        else
            render :new
        end
    end

    def edit
    end

    def update
        @recipe.update(recipe_params)
        if @recipe.valid?
            @recipe.save
            redirect_to recipe_path(@recipe)
        else
            render :edit
        end
    end

    def destroy
        recipe_find.destroy
        redirect_to recipes_path
    end

    private
    def recipe_find
        @recipe = Recipe.find(params[:id])
    end

    def recipe_params
        params.require(:recipe).permit(:title, :ingredients, :instructions, :recipe_id, :user_id, reviews_attributes: [:stars, :comment, :recipe_id, :user_id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :review_find, :redirect_if_not_owner, only: [:show, :update, :edit, :destroy]

    def new
        if params[:recipe_id] && @recipe = Recipe.find_by_id(params[:recipe_id])
            @review = @recipe.reviews.build
        else
            @review = Review.new
            @review.build_recipe
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            #@recipe = RRecipe.find_by_id(params[:recipe_id]) if (params[:recipe_id])
            render :new
        end
    end

    def show
    end
    
    def edit
    end

    def update
        @review.update(review_params)
        if @review.valid?
            @review.save
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    def index
        if params[:recipe_id] && @recipe = Recipe.find_by_id(params[:recipe_id])
            @reviews = @recipe.reviews
        else
            @reviews = Review.all
        end
    end

    def top_rated
        @reviews = Review.all.top_rated 
    end

    def destroy
        review_find.destroy
        redirect_to reviews_path
    end 

    private
        def review_find
            @review = Review.find(params[:id])
        end

        def review_params
            params.require(:review).permit(:stars, :comment, :user_id, :recipe_id, recipes_attributes: [:title, :ingredients, :instructions, :user_id])
        end

        def redirect_if_not_owner
            if current_user != @review.user
                redirect_to user_path(current_user), alert: "Not your recipe!"
            end
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        u = User.find_by_email(params[:email])
        if u && u.authenticate(params[:password])
            session[:user_id] = u.id
            redirect_to recipes_url
        else
            flash[:message] = "Invalid credentials. Please try again"
            redirect_to '/login'
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/login'
    end

    def omniauth
        user = User.create_from_omniauth(auth)

        if user.valid?
            session[:user_id] = user.id
            redirect_to new_recipe_path
        else
            flash[:message] = user.errors.full_messages.join("")
            redirect_to recipes_path
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to recipes_url
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper     
    def display_header(recipe)
        if recipe
            tag.h1("All #{recipe.title}'s Reviews")
        else
            tag.h2("All the Reviews")
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewRecipesRailsproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to("Recipes", recipes_path) %>
    <%= link_to("Make a new recipe", new_recipe_path) %>
    <%= link_to("Reviews", reviews_path) %>
    <%= button_to "Log in with Google", '/auth/google_oauth2' %>
    <%= link_to("Log Out", '/logout', method: 'delete') %>
    
    <hr>

    <% if flash[:message] %>
      <div class="field_with_errors"><%= flash[:message] %> </div>
    <% end %>
    
    
    <%= yield %>
  </body>
</html>

app/views/recipes/_edit_recipe.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :"Recipe title:" %> 
    <%= f.text_field :title %> <br> <br>

    <%= f.label :"List of ingredients:" %> 
    <%= f.text_field :ingredients %> <br> <br>

    <%= f.label :"Recipe instructions:" %> <br>
    <%= f.text_area :instructions %> <br>
    <%= f.submit %>

<% end %>

app/views/recipes/_editform.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :"Recipe title:" %> 
    <%= f.text_field :title %> <br> <br>

    <%= f.label :"List of ingredients:" %> 
    <%= f.text_field :ingredients %> <br> <br>

    <%= f.label :"Recipe instructions:" %> <br>
    <%= f.text_area :instructions %> <br>
    <%= f.submit %>

<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label :"Recipe title:" %> 
    <%= f.text_field :title %> <br> <br>

    <%= f.label :"List of ingredients:" %> 
    <%= f.text_field :ingredients %> <br> <br>

    <%= f.label :"Recipe instructions:" %> <br>
    <%= f.text_area :instructions %> <br>

    <%= f.label :review %> <br>
        <%= f.fields_for :reviews do |r| %> 
        <%= r.hidden_field :user_id, :value => current_user.id %>
        <%= r.label :"Score 0 (lowest) to 5 (highest):" %> <br>
        <%= r.number_field :stars,  min: 0, max: 5, step: 1%> <br> <br>

        <%= r.label :"comment:" %> <br>
        <%= r.text_area :comment %> <br>

        <% end %>

    <%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>
<%= render "edit_recipe", recipe: @recipe %>

app/views/recipes/index.html.erb
<%= flash[:message] %>
<h1> Welcome to your recipe book! </h1> <br>

<ul>
<% @recipes.each do |recipe| %>
 <li> <%= link_to(recipe.title, recipe_path(recipe)) %> </li> <br>
    
<% end %>
</ul>

app/views/recipes/new.html.erb
<h2> Please input your recipe below: </h2> <br>
<%= render "form", recipe: @recipe %>

<% if @recipe.errors.any? %>
<div id = "error_explanation">
    <h2> The <%= pluralize(@recipe.errors.count, "error") %> 
        below is why the recipe could not be saved: </h2>
    
    <ul>
    <% @recipe.errors.full_messages.each do |error| %>
    <li><%= error %> </li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/recipes/show.html.erb
<h1> Recipe Info: </h1>

Title: <%= @recipe.title %> <br>
Ingredients: <%= @recipe.ingredients %> <br>
Instructions: <%= @recipe.instructions %> <br>

Reviews:

<ul><% @recipe.reviews.each do |review| %> <br>
    <li> Comments: <%= review.comment %> </li>
    <li> Score: <%= review.stars %> </li>
<% end %> </ul>
<br>


<%= link_to("Make a new review", new_recipe_review_path(@recipe.id))%> <br>
<%= link_to("Edit Recipe", edit_recipe_path(@recipe.id)) %> <br>
<%= link_to("Delete Recipe", recipe_path(@recipe.id), method: 'delete') %> <br>

app/views/reviews/_form.html.erb
<%= form_for([@recipe, @review]) do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :recipe_id, :value => @review.recipe_id %>
    <%= f.label :"Score 0 (lowest) to 5 (highest):" %> <br>
    <%= f.number_field :stars, min: 0, max: 5, step: 1 %> <br> <br>

    <%= f.label :"comment:" %> <br>
    <%= f.text_area :comment %> <br>

    <%= f.submit %>
    
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>
<%= render "form", review: @review %>

app/views/reviews/index.html.erb
<%= display_header(@recipe) %>

<ul>
<% @reviews.each do |review| %>
<li> <%= link_to(review.comment, review_path(review.id)) %> </li> <br>
    <br>
<% end %>
</ul>

app/views/reviews/new.html.erb
<h1> Add a review to a recipe! </h1>

<%= render "form", review: @review %>

<% if @review.errors.any? %>
<div id = "error_explanation">
    <h2> The <%= pluralize(@review.errors.count, "error") %> 
        below is why the review could not be saved: </h2>
    
    <ul>
    <% @review.errors.full_messages.each do |error| %>
    <li><%= error %> </li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/reviews/show.html.erb
<h1> Review Information: </h1>

Recipe: <%= @review.recipe.title %> <br>
Ingredients: <%= @review.recipe.ingredients %> <br>
Instructions: <%= @review.recipe.instructions %> <br> <br>
Rating: <%= @review.stars %> <br>
Comment: <%= @review.comment %> <br>

<%= link_to("Edit Review", edit_review_path(@review.id)) %> <br>
<%= link_to("Delete Review", review_path(@review.id), method: 'delete') %> <br>

app/views/reviews/top_rated.html.erb
<% @reviews.each do |review| %>
    <%= review.recipe.title %> <br>
    <%= review.stars %> <br>
    <%= review.comment %> <br>
<% end %>

app/views/users/new.html.erb
<%= form_with(model: @user, url:'/signup', local: true) do |f| %>
    <%= f.label :username %> 
    <%= f.text_field :username %> <br> <br>

    <%= f.label :email %> 
    <%= f.email_field :email %> <br> <br>

    <%= f.label :password %> <br>
    <%= f.password_field :password %> <br>

    <%= f.submit "Sign Up"%>

<% end %>